/*
 * Copyright (c) Microsoft and contributors.  All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * 
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

var msRestAzure = require('ms-rest-azure');

exports.BaseResource = msRestAzure.BaseResource;
exports.CloudError = msRestAzure.CloudError;
exports.Sku = require('./sku');
exports.SubResource = require('./subResource');
exports.Resource = require('./resource');
exports.Server = require('./server');
exports.ServerUpdateParameters = require('./serverUpdateParameters');
exports.FirewallRule = require('./firewallRule');
exports.Database = require('./database');
exports.ServerListResult = require('./serverListResult');
exports.FirewallRuleListResult = require('./firewallRuleListResult');
exports.DatabaseListResult = require('./databaseListResult');
